apiVersion: v1
kind: Service
metadata:
  name: verifier-{{ $.Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: verifier-{{ $.Release.Name }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.grpcPort }}
      targetPort: 5000
